import {
  Ambulance,
  BadgeCheck,
  CarFront,
  CircleX,
  CloudRain,
  CloudRainWind,
  Construction,
  Cross,
  Droplets,
  FireExtinguisher,
  Flame,
  House,
  HouseHeart,
  LocateFixed,
  MapPin,
  MapPinned,
  Mountain,
  PackageOpen,
  Plane,
  RadioTower,
  Search,
  Shield,
  ShieldCheck,
  ShipWheel,
  TentTree,
  Truck,
  UsersRound,
  Utensils,
  Warehouse,
  Waves,
  Vibrate,
  ZapOff,
  type LucideIcon,
} from 'lucide-react';
import { PLANNING_SYMBOLS } from './planning';

type PlanningSymbolKey = typeof PLANNING_SYMBOLS[number]['key'];

const icons: Record<PlanningSymbolKey, LucideIcon> = {
  eoc: RadioTower,
  icp: ShieldCheck,
  staging: MapPinned,
  checkpoint: BadgeCheck,
  'evacuation-center': HouseHeart,
  'medical-post': Cross,
  'search-rescue': Search,
  'fire-service': FireExtinguisher,
  police: Shield,
  'relief-goods': PackageOpen,
  food: Utensils,
  water: Droplets,
  'temporary-shelter': TentTree,
  warehouse: Warehouse,
  ambulance: Ambulance,
  'rescue-truck': Truck,
  'rescue-boat': ShipWheel,
  helicopter: Plane,
  'pickup-point': LocateFixed,
  'road-closure': CircleX,
  'damaged-bridge': Construction,
  'stranded-people': UsersRound,
  'affected-structure': House,
  'power-outage': ZapOff,
  flood: CloudRain,
  'storm-surge': CloudRainWind,
  landslide: Mountain,
  earthquake: Vibrate,
  tsunami: Waves,
  'vehicular-incident': CarFront,
  'fire-incident': Flame,
};

export function getPlanningSymbolIcon(key?: string) {
  return icons[key as PlanningSymbolKey] ?? MapPin;
}
